# Generated by Django 4.1 on 2024-05-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0002_remove_user_funkos_user_funkos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('club', models.CharField(max_length=128)),
                ('pais', models.CharField(max_length=128)),
                ('retirado', models.BooleanField(default=False)),
            ],
        ),
    ]
