# Generated by Django 4.1 on 2024-05-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0003_jugador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
